/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figurasgeametricas;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author raymundo
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        panelesdeTrabajo = new javax.swing.JPanel();
        panelAreaCirculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRadioCirculo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAreaCirculo = new javax.swing.JTextField();
        panelAreaRectangulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBaseRectangulo = new javax.swing.JTextField();
        jTextFieldAlturaRectangulo = new javax.swing.JTextField();
        jTextFieldAreaRectangulo = new javax.swing.JTextField();
        panelAreaTriangulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBaseTriangulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAlturaTriangulo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAreaTriangulo = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 452));
        setSize(new java.awt.Dimension(630, 452));

        panelesdeTrabajo.setLayout(new java.awt.CardLayout());

        panelAreaCirculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Area Circulo.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelAreaCirculo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 5, -1, -1));

        jLabel4.setText("Radio: ");
        panelAreaCirculo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));
        panelAreaCirculo.add(jTextFieldRadioCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 170, -1));

        jButton1.setText("Calcular Area.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelAreaCirculo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel5.setText("Resultado: ");
        panelAreaCirculo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));
        panelAreaCirculo.add(jTextFieldAreaCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 170, -1));

        panelesdeTrabajo.add(panelAreaCirculo, "cardAreaCirculo");

        panelAreaRectangulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Area Rectangulo");
        panelAreaRectangulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 5, -1, -1));

        jLabel6.setText("Base: ");
        panelAreaRectangulo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 40, 10));

        jLabel7.setText("Altura: ");
        panelAreaRectangulo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 90, 40, -1));

        jButton2.setText("Calcular Area");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelAreaRectangulo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel8.setText("Resultado: ");
        panelAreaRectangulo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        panelAreaRectangulo.add(jTextFieldBaseRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, -1));
        panelAreaRectangulo.add(jTextFieldAlturaRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 90, -1));
        panelAreaRectangulo.add(jTextFieldAreaRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, -1));

        panelesdeTrabajo.add(panelAreaRectangulo, "cardAreaRectangulo");

        panelAreaTriangulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Area Triangulo");
        panelAreaTriangulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 5, -1, -1));

        jLabel9.setText("Base: ");
        panelAreaTriangulo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, 10));
        panelAreaTriangulo.add(jTextFieldBaseTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 90, -1));

        jLabel10.setText("Altura: ");
        panelAreaTriangulo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, -1));
        panelAreaTriangulo.add(jTextFieldAlturaTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, -1));

        jButton3.setText("Calcular Area");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelAreaTriangulo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel11.setText("Resultado: ");
        panelAreaTriangulo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));
        panelAreaTriangulo.add(jTextFieldAreaTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, -1));

        panelesdeTrabajo.add(panelAreaTriangulo, "cardAreaTriangulo");

        getContentPane().add(panelesdeTrabajo, java.awt.BorderLayout.CENTER);

        jMenu3.setText("area");

        jMenuItem5.setText("areacirculo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem3.setText("arearectangulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem8.setText("areatriangulo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("perimetro");

        jMenuItem7.setText("perimetrocirculo");
        jMenu4.add(jMenuItem7);

        jMenuItem9.setText("perimetrotriangulo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("perimetrotriangulo");
        jMenu4.add(jMenuItem10);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("salir");
        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout cl= (CardLayout) panelesdeTrabajo.getLayout();
        cl.show(panelesdeTrabajo, "cardAreaRectangulo");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         CardLayout cl= (CardLayout) panelesdeTrabajo.getLayout();
        cl.show(panelesdeTrabajo, "cardAreaTriangulo");
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       arearectangulo ar = new arearectangulo();
        ar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl= (CardLayout) panelesdeTrabajo.getLayout();
        cl.show(panelesdeTrabajo, "cardAreaCirculo");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String textoRadioCirculo;
        textoRadioCirculo = jTextFieldRadioCirculo.getText();
        double radioCirculo = Float.parseFloat(textoRadioCirculo);
        jTextFieldAreaCirculo.setText("" + (Math.PI * radioCirculo * radioCirculo));
        try{
            
        }
        catch(NumberFormatException ex)
        {   JOptionPane.showMessageDialog(rootPane, "El valor para el radio del circulo(" + textoRadioCirculo + ") no es valido.");
            jTextFieldRadioCirculo.setText("");
            jTextFieldAreaCirculo.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String textoBaseRectangulo;
        String textoAlturaRectangulo;
        textoBaseRectangulo = jTextFieldBaseRectangulo.getText();
        textoAlturaRectangulo = jTextFieldAlturaRectangulo.getText();
            
        try{
            
            float baseRectangulo = Float.parseFloat(textoBaseRectangulo);
            float alturaRectangulo = Float.parseFloat(textoAlturaRectangulo);
            jTextFieldAreaRectangulo.setText("" + ( baseRectangulo * alturaRectangulo));
        }
        catch(NumberFormatException ex)
        {   JOptionPane.showMessageDialog(rootPane, "El valor de la base(" + textoBaseRectangulo + ") o de la altura (" + textoAlturaRectangulo+ ") del rectangulo no son validos.");
            jTextFieldBaseRectangulo.setText("");
            jTextFieldAlturaRectangulo.setText("");
            jTextFieldAreaRectangulo.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String textoBaseTriangulo;
        String textoAlturaTriangulo;
        textoBaseTriangulo = jTextFieldBaseTriangulo.getText();
        textoAlturaTriangulo = jTextFieldAlturaTriangulo.getText();
            
        try{
            
            float baseTriangulo = Float.parseFloat(textoBaseTriangulo);
            float alturaTriangulo = Float.parseFloat(textoAlturaTriangulo);
            jTextFieldAreaTriangulo.setText("" + ( baseTriangulo * alturaTriangulo / 2));
        }
        catch(NumberFormatException ex)
        {   JOptionPane.showMessageDialog(rootPane, "El valor de la base(" + textoBaseTriangulo + ") o de la altura (" + textoAlturaTriangulo+ ") del triangulo no son validos.");
            jTextFieldBaseTriangulo.setText("");
            jTextFieldAlturaTriangulo.setText("");
            jTextFieldAreaTriangulo.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTextField jTextFieldAlturaRectangulo;
    private javax.swing.JTextField jTextFieldAlturaTriangulo;
    private javax.swing.JTextField jTextFieldAreaCirculo;
    private javax.swing.JTextField jTextFieldAreaRectangulo;
    private javax.swing.JTextField jTextFieldAreaTriangulo;
    private javax.swing.JTextField jTextFieldBaseRectangulo;
    private javax.swing.JTextField jTextFieldBaseTriangulo;
    private javax.swing.JTextField jTextFieldRadioCirculo;
    private javax.swing.JPanel panelAreaCirculo;
    private javax.swing.JPanel panelAreaRectangulo;
    private javax.swing.JPanel panelAreaTriangulo;
    private javax.swing.JPanel panelesdeTrabajo;
    // End of variables declaration//GEN-END:variables
}
